### ISSUE TITLE
當 sprite.hidden = true 時，是否應該被 click & touch 忽略？ => YES

### ISSUE THREAD

**Issue by kevin-shu** [OrangeAppleTW/engine.js#16]

**Comment by wacamoto** [comment]
客製化提供兩種屬性 transparent、visible

**Sprite.transparen**t(number) 角色透明度，值介於 0 ~ 1
**Sprite.hidden**(boolean) 隱藏角色，點擊和觸碰事件不會被觸發

**Comment by kevin-shu** [comment]
cool, 那就姑且讓 sprite 在 hidden 的時候碰不到囉~

**Comment by kevin-shu** [comment]
done 442b2dabda3c25c80c927abc9c3909e93f4079ea
