### ISSUE TITLE
客製化 Sprites 繪製的先後順序

### ISSUE THREAD

**Issue by wacamoto** [OrangeAppleTW/engine.js#17]
能否為 Sprite 增加一個 layer 的屬性用於繪圖的先後順序

**Comment by kevin-shu** [comment]
@wacamoto 這樣的設計可以嗎？
![image](https://cloud.githubusercontent.com/assets/2299874/24325487/f0f17dd0-11d4-11e7-9d8b-6858e8cac5eb.png)

**Comment by kevin-shu** [comment]
@wacamoto 我沒看到你的內文，我覺得用 layer 比較好

**Comment by kevin-shu** [comment]
done 476aadc5c00e461f07bf773a3b0cbe5419021024
