### ISSUE TITLE
能夠設定角色的外觀是否旋轉

### ISSUE THREAD

**Issue by kevin-shu** [OrangeAppleTW/engine.js#20]

**Comment by wacamoto** [comment]
像 scratch 那樣能設定旋轉的屬性 ？

**Comment by kevin-shu** [comment]
對呀，但是我覺得就設定為「能轉」and「不能轉」就好

**Comment by wacamoto** [comment]
設定左右翻轉也很實用呀，這樣人物圖片素材就可以重複使用
![right](https://cloud.githubusercontent.com/assets/11512562/24299720/109fcb96-10e5-11e7-80dc-455df95bb8f0.png)
![left](https://cloud.githubusercontent.com/assets/11512562/24299722/11d2d51c-10e5-11e7-85d5-b4f75389c01d.png)

**Comment by kevin-shu** [comment]
當然好，那就這三種吧！
