### ISSUE TITLE
remove Game.on("touched", ...) method

### ISSUE THREAD

**Issue by wacamoto** [OrangeAppleTW/engine.js#25]
Game.on("click", ...) 跟 Game.on("hover", ...) 也要移除嗎

**Comment by kevin-shu** [comment]
對吼

**Comment by wacamoto** [comment]
Game.on("click", Game.sprites.hero, function(){ /* Do something */ });
更改為
Game.on("click", function(){ /* Do something */ });

**Comment by kevin-shu** [comment]
@wacamoto 那就把 touched & hover 移掉吧~
