### ISSUE TITLE
[提案] 畫筆功能

### ISSUE THREAD

**Issue by kevin-shu** [OrangeAppleTW/engine.js#38]
```javascript
Game.pen.moveTo(0,0);
Game.pen.color = "#ff0000";
Game.pen.size = 4;
Game.pen.down();
Game.pen.moveTo(200,200);
Game.pen.up();
```

@wacamoto 你覺得呢？

**Comment by wacamoto** [comment]
`
Game.pen.color = "#ff0000";
Game.pen.size = 4;
Game.pen.fill = "blue";
var config = {} // 可以覆蓋預設 pen 的屬性
Game.pen.line(x1, y1, x2, y2, config);
Game.pen.circle(x, y, diameter, config);
Game.pen.rect(x, y, width, height, config);
Game.pen. polygon([x1, y1, x2, y2, x3, y3, ...], config);

// 提供儲存方法，不用在每次 forever 裡再畫
// 提供更多的屬性可以操作
var circle = Game.pen.circle(x, y, diameter);
Game.gemo.add(circle);
`

**Comment by wacamoto** [comment]
參考 p5 跟 Phaser.Geometry

**Comment by kevin-shu** [comment]
我還在想加上幾何繪製有沒有必要，你覺得什麼情況會用到呀？

**Comment by wacamoto** [comment]
如果調整迴圈裡函式的順序，就不能讓使用者直接拿 ctx 畫圖
