### ISSUE TITLE
修改 shapes 的繪畫順序

### ISSUE THREAD

**Issue by kevin-shu** [OrangeAppleTW/engine.js#79]
照理說 render 順序應該是：
1. 背景
2. 幾何
3. 角色
4. 文字

所以照理來說，應該可以不用特別存 shapes (但是要存 text)，於是將傳進 Clock 的 function 修成這樣：
1. drawBackdrop
2. 執行 update 的 function (形狀直接畫，文字存起來)
3. drawSprites
4. printText，接著將存起來的 text 清掉

**Comment by wacamoto** [comment]
遊戲迴圈：邏輯 -> 繪圖 -> 邏輯 -> 繪圖 ...
只要用繪筆存起來的主因是如果是在事件裡觸發畫圖，事件觸發是邏輯所以沒有存起來都會被背景蓋掉

**Comment by kevin-shu** [comment]
修改了機制，變成：

1. drawBackdrop
2. 執行 update 的 function (形狀直接畫，文字存起來)
3. drawSprites
4. printText，接著將存起來的 text 清掉

已 close: 045c898cb33a1064870f04fe5c7e696faccbe5b5
